//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppOfHotal.Models
{
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class booking
    {
        public int id { get; set; }
        public int ssn_cust { get; set; }
        public int id_hostal { get; set; }
        [BindProperty, DataType(DataType.DateTime)]
        public Nullable<System.DateTime> booking_date { get; set; }
        [BindProperty, DataType(DataType.Date)]
        public Nullable<System.DateTime> check_in { get; set; }
        [BindProperty, DataType(DataType.Date)]
        public Nullable<System.DateTime> check_out { get; set; }
        public Nullable<int> state_booking { get; set; }
        public Nullable<int> cr_user { get; set; }
        public Nullable<int> is_checking { get; set; }
    
        public virtual checking checking { get; set; }
        public virtual customer customer { get; set; }
        public virtual hostal hostal { get; set; }
        public virtual state_booking state_booking1 { get; set; }
    }
}
