//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppOfHotal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.bookings = new HashSet<booking>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public int gender { get; set; }
        public Nullable<int> type_doc { get; set; }
        public Nullable<int> nationalty { get; set; }
        public string serial_number { get; set; }
        public Nullable<int> cr_user { get; set; }
        public Nullable<System.DateTime> cr_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
        public virtual gender gender1 { get; set; }
        public virtual Nationalty Nationalty1 { get; set; }
        public virtual type_documant type_documant { get; set; }
    }
}
