//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppOfHotal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class days_booking
    {
        public int id_booking { get; set; }
        public int amount_days { get; set; }
        public int spend_days { get; set; }
        public int rest_days { get; set; }
        public Nullable<System.DateTime> upd_date { get; set; }
    }
}
