//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppOfHotal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hostal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hostal()
        {
            this.bookings = new HashSet<booking>();
        }
    
        public int id { get; set; }
        public string title_hostal { get; set; }
        public Nullable<int> beds { get; set; }
        public Nullable<int> for_how { get; set; }
        public Nullable<int> rooms { get; set; }
        public Nullable<int> id_class { get; set; }
        public Nullable<int> id_state { get; set; }
        public Nullable<int> cr_user { get; set; }
        public Nullable<System.DateTime> cr_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
        public virtual hostal_state hostal_state { get; set; }
        public virtual Types_hostal Types_hostal { get; set; }
    }
}
