//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppOfHotal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class al_hotalEntities : DbContext
    {
        public al_hotalEntities()
            : base("name=al_hotalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<checking> checkings { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<days_booking> days_booking { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<hostal> hostals { get; set; }
        public virtual DbSet<hostal_state> hostal_state { get; set; }
        public virtual DbSet<Nationalty> Nationalties { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<state_booking> state_booking { get; set; }
        public virtual DbSet<type_documant> type_documant { get; set; }
        public virtual DbSet<Types_hostal> Types_hostal { get; set; }
    }
}
