//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppOfHotal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int id { get; set; }
        public int id_bookings { get; set; }
        public decimal total { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> payment1 { get; set; }
        public Nullable<decimal> nets { get; set; }
    }
}
