//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppOfHotal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Types_hostal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Types_hostal()
        {
            this.hostals = new HashSet<hostal>();
        }
    
        public int id { get; set; }
        public string types { get; set; }
        public int price { get; set; }
        public int cr_user { get; set; }
        public System.DateTime cr_date { get; set; }
        public Nullable<int> upd_user { get; set; }
        public Nullable<System.DateTime> upd_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hostal> hostals { get; set; }
    }
}
